spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
    url: jdbc:mysql://localhost:3306/
    username: root
    password: admin
          
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 36000